### ISSUE TITLE
Fresh Install expects last_run file to be there. 

### ISSUE THREAD

**Issue by rfun** [rileyhales/gldas#3]
A fresh install on the new server gives the following error. 

`ERROR Internal Server Error: /apps/gfs/
Traceback (most recent call last):
  File "/media/root/tethys/main/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/media/root/tethys/main/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/media/root/tethys/main/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/root/tethys/main/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/root/tethys/main/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/media/root/tethys/main/tethys/src/tethys_apps/tethysapp/gfs/controllers.py", line 45, in home
    current_gfs_time = currentgfs()
  File "/media/root/tethys/main/tethys/src/tethys_apps/tethysapp/gfs/options.py", line 102, in currentgfs
    timestamp = gettimestamp()
  File "/media/root/tethys/main/tethys/src/tethys_apps/tethysapp/gfs/options.py", line 23, in gettimestamp
    with open(os.path.join(path, 'last_run.txt'), 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/media/root/tethys/main/thredds/data/thredds/public/gfs/last_run.txt'
[pid: 28145|app: 0|req: 1/18] 136.36.97.224 () {46 vars in 2047 bytes} [Mon Jul  8 06:25:55 2019] GET /apps/gfs/ => generated 8961 bytes in 663 msecs (HTTP/1.1 500) 4 headers in 143 bytes (1 switches on core 0)

`

Could you please fix the issue and let me know when the code is ready to pull? Thanks

**Comment by rileyhales** [comment]
Its actually not a bug, you just have to touch last_run.txt before you can run the workflow. It doesn't have to have information in it yet. However i'm about to push a bunch of new features to the app and that will address the case where you try to run the workflow without having created that file first. By tomorrow i'll have it tested and pushed so we can just wait until then.

**Comment by rileyhales** [comment]
Also this is an issue for the GFS app, not the GLDAS app, but thats fine

**Comment by rfun** [comment]
Gotcha! Thanks man. Sorry I posted it in the wrong app. Lol too many apps in my head!
